<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Inherit common configuration and dependency management from parent -->
    <parent>
        <groupId>org.grnet</groupId>
        <artifactId>status</artifactId>
        <version>${revision}</version>
    </parent>

    <!-- Module coordinates -->
    <artifactId>status-mappers</artifactId>
    <name>status-mappers</name>
    <version>${revision}</version>
    <dependencies>
        <!-- MapStruct for automatic mapping between DTOs and Entities -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
        </dependency>

        <!-- Internal DTO module used in mapper definitions -->
        <dependency>
            <groupId>org.grnet</groupId>
            <artifactId>status-data-transfer-objects</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.grnet</groupId>
            <artifactId>status-entities</artifactId>
            <version>${revision}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.smallrye</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
